version: 2
jobs:
  build:
    machine:
      enabled: true
    working_directory: ~
    steps:
      - checkout
      - run: ./gradlew build --stacktrace -Dorg.gradle.java.home=/usr/lib/jvm/java-17-openjdk-amd64
      - store_test_results:
          path: build/parnas/test-results
  release:
    machine:
      enabled: true
    working_directory: ~
    steps:
      - checkout
      - run: ./gradlew githubRelease -Dorg.gradle.java.home=/usr/lib/jvm/java-17-openjdk-amd64

workflows:
  version: 2
  build-test-and-release:
    jobs:
      - build
      - approve-release:
          type: approval
          requires:
            - build
          filters:
            branches:
              only: master
      - release:
          requires:
            - approve-release
          filters:
            branches:
              only: master
